# ruff: noqa: E501,I001
"""Generate the DIMER Table Intelligence workshop notebook.

Besides the cells of ``table_intelligence_workshop_source.py`` the notebook carries two files byte-for-byte,
in its carrier cell (id ``uvcarrier``), and verifies their SHA-256 before use:

* ``table_intelligence_workshop.py``  <- ``tools/table_intelligence_workshop.py`` (every stage), and
* ``requirements.lock.txt``           <- ``tools/table-intelligence-workshop-requirements.lock``
  (``uv pip compile --generate-hashes`` for CPython 3.12 on ``x86_64-manylinux_2_28``).

Each carried string is written as an implicitly concatenated run of pieces of at most 1,000 characters,
split at line boundaries, so no notebook line is long enough to stall the Colab editor. ``--check`` fails
when the notebook differs from the cells or from either carried file.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
from table_intelligence_workshop_source import CELLS

NOTEBOOK_NAME = "DIMER_Table_Intelligence_Workshop.ipynb"
TOOLS = Path(__file__).resolve().parent
CARRIED = {
    "table_intelligence_workshop.py": TOOLS / "table_intelligence_workshop.py",
    "requirements.lock.txt": TOOLS / "table-intelligence-workshop-requirements.lock",
}
PIECE_LIMIT = 1000
DIMER_METADATA = {
    "notebook_spec": "2.1",
    "notebook_profile": "TASK-INFERENCE",
    "profile": "TASK-INFERENCE",
    "notebook_mode": "WORKSHOP",
    "workflow_scope": "COMPOSED-PIPELINE",
    "standalone": True,
    "canonical_runtime": "NVIDIA Tesla T4",
    "worker_required": False,
    "credentials_required": False,
    "clean_runtime_evidence": "pending",
    "dataset": {
        "id": "bevaya/SciTSR-pd",
        "license": "CC0-1.0",
        "revision": "dae336efa7af07d69194a510ff5568980e8ef253"
    },
    "models": [
        {
            "id": "microsoft/table-transformer-detection",
            "revision": "2357cbe2b5a5d1c03e54f32764f06058933b65ab"
        },
        {
            "id": "microsoft/table-transformer-structure-recognition-v1.1-all",
            "revision": "7587a7ef111d9dcbf8ac695f1376ab7014340a0c"
        },
        {
            "id": "google/tapas-large-finetuned-wtq",
            "revision": "f58317ab2577d17647d9acafa790c744a0388b30"
        }
    ],
    "generated_from": {
        "repository": "kurtvalcorza/table-transformer-structure-pipeline",
        "source": "tools/table_intelligence_workshop_source.py",
        "generator": "tools/build_table_intelligence_workshop.py"
    },
    "review_revisions": [
        {
            "review": "docs/reviews/2026-10-02-notebook-review/DIMER_Table_Intelligence_Workshop_Review.md",
            "base_commit": "c218d3119e157293949862d6972e77d4a029c6b0",
            "fixed": ["TBL-M1", "TBL-M2", "TBL-M3", "TBL-m1", "TBL-m2", "TBL-m3", "TBL-m4", "TBL-m5", "TBL-m6", "TBL-m7"]
        },
        {
            "revision": "0.3.0-candidate",
            "date": "2026-10-03",
            "base_commit": "a043211deeb9d62d5cc9864bc6ac37123fe1f8d6",
            "change": "uv isolated environment: no kernel install and no restart guard; every stage runs as a separate process with the Python of a hash-locked CPython 3.12.12 venv; Linux x86_64 only",
            "fixes_kept": ["TBL-M1", "TBL-M2", "TBL-M3", "TBL-m1", "TBL-m2", "TBL-m3", "TBL-m4", "TBL-m5", "TBL-m6", "TBL-m7"]
        }
    ],
    "runtime_environment": {
        "platform": "Linux x86_64 only (Google Colab, Kaggle, Linux Jupyter)",
        "python": "CPython 3.12.12 (uv managed)",
        "uv": "0.12.15 (wheel pinned by size and SHA-256)",
        "install": "uv pip install --require-hashes --only-binary :all: -r requirements.lock.txt",
        "kernel_installs": "none; no restart"
    }
}


def pieces(text, limit=PIECE_LIMIT):
    out = []
    current = ""
    for line in text.splitlines(keepends=True):
        if current and len(current) + len(line) > limit:
            out.append(current)
            current = ""
        current += line
    if current:
        out.append(current)
    return out


def carried_texts():
    texts = {}
    for name, path in CARRIED.items():
        data = path.read_bytes()
        if b"\r" in data:
            raise SystemExit(f"{path} must use LF line endings")
        texts[name] = data.decode("utf-8")
    return texts


def carried_hashes(texts):
    return {name: hashlib.sha256(text.encode("utf-8")).hexdigest() for name, text in texts.items()}


def carrier_source(texts):
    lines = [
        "# Carried stage file and hash lock (infrastructure)",
        "# Generated by tools/build_table_intelligence_workshop.py; do not edit by hand.",
        "from pathlib import Path",
        "CARRIED_FILES = {",
    ]
    for name, text in texts.items():
        lines.append(f" {name!r}: (")
        lines.extend(f"  {piece!r}" for piece in pieces(text))
        lines.append(" ),")
    lines.append("}")
    lines.append("CARRIED_HASHES = {")
    lines.extend(f" {name!r}: {digest!r}," for name, digest in carried_hashes(texts).items())
    lines.append("}")
    lines += [
        "WORK_ROOT = Path(WORK_DIR)",
        "RUNNER_ROOT = WORK_ROOT / 'runner'",
        "for name, text in CARRIED_FILES.items():",
        "    path = RUNNER_ROOT / name",
        "    path.parent.mkdir(parents=True, exist_ok=True)",
        "    path.write_text(text, encoding='utf-8', newline='\\n')",
        "    if __import__('hashlib').sha256(path.read_bytes()).hexdigest() != CARRIED_HASHES[name]:",
        "        raise RuntimeError('Carried file integrity failure: ' + name)",
        "print('Carried stage file and hash lock verified:', sorted(CARRIED_FILES))",
    ]
    return "\n".join(lines)


def build_notebook():
    rendered = []
    texts = carried_texts()
    index = 0
    for cell in CELLS:
        # Infrastructure cells (GDL11) are collapsed where the notebook viewer supports it.
        metadata = {"jupyter": {"source_hidden": True}} if cell.get("infrastructure") else {}
        source = carrier_source(texts) if cell.get("carrier") else cell["source"]
        # Cells added after 0.2.0 carry their own id, so the numbered ids of the original cells do not move.
        cell_id = cell.get("id") or f"dimer-table-workshop-{index:02d}"
        if not cell.get("id"):
            index += 1
        base = {"id": cell_id, "metadata": metadata, "source": source.splitlines(keepends=True)}
        if cell["kind"] == "markdown":
            rendered.append({"cell_type": "markdown", **base})
        else:
            rendered.append({"cell_type": "code", "execution_count": None, "outputs": [], **base})
    return {
        "cells": rendered,
        "metadata": {
            "accelerator": "GPU",
            "colab": {"gpuType": "T4", "provenance": []},
            "dimer": {
                **DIMER_METADATA,
                "carried_files": {
                    name: {"source": f"tools/{CARRIED[name].name}", "sha256": digest}
                    for name, digest in carried_hashes(texts).items()
                },
            },
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "workshop_revision": "0.3.0-candidate",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def serialized():
    return json.dumps(build_notebook(), indent=1, ensure_ascii=False) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    out = args.out or repo / "tutorials" / NOTEBOOK_NAME
    content = serialized()
    if args.check:
        if not out.exists() or out.read_text(encoding="utf-8") != content:
            raise SystemExit(f"STALE: {out}; regenerate the workshop notebook")
        print(f"OK: {out}")
        return 0
    out.write_text(content, encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
